language: node_js
node_js:
- 6.1
before_script:
- npm install -g gulp
- npm install -g bower
- bower install
script:
- gulp rebuild
- gulp deploy
before_install:
- openssl aes-256-cbc -K $encrypted_fdaada7ca890_key -iv $encrypted_fdaada7ca890_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar zxvf secrets.tar.gz
