language: node_js
node_js:
- 0.10.40
before_script:
- npm install -g gulp
- npm install -g bower
- bower install
script: gulp deploy
before_install:
- openssl aes-256-cbc -K $encrypted_d5dc8dc61da0_key -iv $encrypted_d5dc8dc61da0_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar zxvf secrets.tar.gz
